# Generated by Django 3.2.18 on 2023-04-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_has_reporter',
            name='Project_Reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_app.reporter'),
        ),
    ]
