# Generated by Django 3.2.18 on 2023-04-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Project',
        ),
    ]
