# Generated by Django 3.2.18 on 2023-04-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_project_has_reporter_project_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_has_reportee',
            name='Project_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.project_has_reporter'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
