# Generated by Django 3.2.18 on 2023-04-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_reportee_reporter'),
        ('task', '0002_rename_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Has_Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('Project_Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.reporter')),
            ],
        ),
    ]
