# Generated by Django 3.2.18 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_project_has_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('task_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_task',
            field=models.ManyToManyField(to='task.Project_Task'),
        ),
    ]
