# Generated by Django 3.2.18 on 2023-04-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
        ('task', '0003_auto_20230413_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_has_reportee',
            name='Project_info',
        ),
        migrations.AddField(
            model_name='task_has_reportee',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.project'),
        ),
        migrations.AddField(
            model_name='task_has_reportee',
            name='Reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.reporter'),
        ),
    ]
