# Generated by Django 3.2.18 on 2023-04-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20230411_0932'),
        ('task', '0004_auto_20230411_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_has_reporter',
            unique_together={('Project_Reporter', 'Project_Name')},
        ),
    ]
