# Generated by Django 3.2.18 on 2023-04-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_project_has_reporter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_task',
        ),
    ]
