# Generated by Django 3.2.18 on 2023-04-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_project_project_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_has_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('Project_Task', models.ManyToManyField(to='task.Project_Task')),
            ],
        ),
        migrations.AlterField(
            model_name='project_has_reporter',
            name='Project_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project_has_task'),
        ),
    ]
