# Generated by Django 3.2.18 on 2023-04-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20230414_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
