# Generated by Django 3.2.18 on 2023-04-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20230411_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_has_reporter',
            name='Project_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project'),
        ),
        migrations.DeleteModel(
            name='Project_has_Task',
        ),
    ]
