# Generated by Django 3.2.18 on 2023-04-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20230414_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_has_reportee',
            name='expected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
