# Generated by Django 3.2.18 on 2023-04-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20230411_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Task',
            new_name='Task',
        ),
    ]
