# Generated by Django 3.2.18 on 2023-04-11 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_rename_project_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_has_task',
            name='Project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.project'),
        ),
    ]
