# Generated by Django 3.2.18 on 2023-04-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_project_has_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_has_task',
            name='Project_Task',
        ),
        migrations.AddField(
            model_name='project_has_task',
            name='Project_Task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
