# Generated by Django 3.2.18 on 2023-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20230411_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_has_task',
            name='Project_Task',
        ),
        migrations.AddField(
            model_name='project_has_task',
            name='Project_Task',
            field=models.ManyToManyField(to='task.Task'),
        ),
    ]
