# Generated by Django 3.2.18 on 2023-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20230411_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_has_reportee',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='ToDo', max_length=250),
        ),
    ]
