# Generated by Django 3.2.18 on 2023-04-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20230411_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportee',
            name='is_reportee',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='is_admin',
        ),
    ]
